### ISSUE TITLE
Font is appearing flipped both vertically and horizontally

### ISSUE THREAD

**Issue by nlfonseca** [Experience-Monks/three-bmfont-text#25]
Hi, I'm trying to integrate your lib into my existing THREE.js project, but when adding the text to the scene, it appears flipped vertically and horizontally (see picture below).

![image](https://user-images.githubusercontent.com/7745591/36253677-24a9c6e8-1240-11e8-8c8e-57d2082c6331.png)

When I use the `createOrbitViewer` utilitary — as in the examples —, it appears OK, but as soon as I switch to a regular `PerspectiveCamera`, that happens. 

I've made sure that no rotation and translations are being made to the text (I'm just adding it to the `0,0,0` position) , and I've placed my camera on the coordinates `0,0,50`, facing the centre of the scene.

I've also tried to set the `flipY` property to false, but it doesn't render when I do so.

Any tips on solving this?

Thanks in advance.

**Comment by antoniocapelo** [comment]
any update on this issue?

**Comment by pablokvitca** [comment]
Try just rotating the mesh using .rotateX(Math.PI) and .rotateY(Math.PI), worked for me

**Comment by nlfonseca** [comment]
Thanks @pablokvitca ! 
That was what I ended up doing 😄
